danstis/go-nitrado

- .deepsource.toml
- .github/workflows/build.yml
- README.md
> docs(readme): add deepsource badge

- README.md
> docs: add build badge to readme

- README.md
> docs: update readme link

- .github/workflows/build.yml
> build: add codecov coverage

- nitrado/nitrado.go
> fix: return value of `io.Copy` is not checked

- nitrado/service.go
- nitrado/service_test.go
> feat: add method to get a detailed service

- nitrado/nitrado_test.go
> test: add additional tests

- .editorconfig
- .github/workflows/build.yml
- README.md
> docs: add code climate badge

- example/simple/main.go
> docs(example): update example to use environment vars

- .codecov.yml
> build: add codecov config

- .deepsource.toml
- nitrado/gameserver_fileserver.go
- nitrado/gameserver_fileserver_test.go
- nitrado/models.go
- nitrado/nitrado.go
> feat: add method to get a list of LogFiles

- .github/workflows/build.yml
- .github/workflows/release.yml
> build: update build process to create releases on GitHub

- nitrado/gameserver_fileserver.go
- nitrado/gameserver_fileserver_test.go
> feat: add method to get a download link for a service and file

- nitrado/gameserver.go
- nitrado/gameserver_test.go
> feat: add method to restart a gameserver

- nitrado/gameserver.go
> fix: update error string format

- .github/workflows/build.yml
> build: change tagging step to use new action

- README.md
- nitrado/gameserver_fileserver_test.go
- nitrado/gameserver_settings_test.go
- nitrado/gameserver_test.go
- nitrado/nitrado_test.go
- nitrado/service_test.go
> docs: update readme and test comments

- nitrado/gameserver_fileserver.go
- nitrado/gameserver_fileserver_test.go
> feat: remove pointers from file output

- nitrado/nitrado.go
> feat: remove mutex on do method

- nitrado/gameserver_fileserver.go
- nitrado/gameserver_fileserver_test.go
> feat: add upload method

- .github/workflows/build.yml
- sonar-project.properties
> ci: add sonarcloud config

- nitrado/gameserver_stats.go
- nitrado/gameserver_stats_test.go
- nitrado/nitrado.go
> Add support for gameserver stats

- nitrado/gameserver_stats.go
- nitrado/gameserver_stats_test.go
> fix: fix issue with ints in GSStats

- nitrado/nitrado.go
> fix: code always retries regardless of outcome of the call

- nitrado/nitrado_test.go
> chore: remove github references in nitrado_test.go

- .github/workflows/build.yml
Fixes #94
<sub><img src="https://user-images.githubusercontent.com/4775299/87437657-e7332b00-c5ee-11ea-958d-589dfb19d72c.png" alt=" " width="10" height="9"> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>
> ci: update to handle dependabot PRs

- .github/workflows/build.yml
- go.mod
- go.sum
- nitrado/gameserver.go
- nitrado/gameserver_test.go
> feat: add support for the dayz config file config setting

- .github/workflows/build.yml
> ci: update golanglint-ci to use latest version

- README.md
Fixes #142
___
Bug fix
___
- Update GitHub Actions build/test badge URL
- Replace CodeClimate badge with SonarCloud badge
- Fix broken README badge links
___
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Fix broken README badges</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<ul><li>Updated build/test badge to use actions/workflows/build.yml<br> <li> Replaced …
> fix: update broken README badges
